### PR TITLE
Fix typo of "Communication"

### PR DESCRIPTION
**Pull request by adamnbowen**
"Communictation" -> "Communication"

### CODE REVIEW

**Comment by cr8onski** [comment]
Good catch, and thanks for the pull request.  Can you make the pull request to the adlnet development branch rather than master.  That will let this fix bubble up through our regular process.

**Comment by adamnbowen** [comment]
@cr8onski done

**Comment by cr8onski** [comment]
Thanks @adamnbowen

**Comment by adamnbowen** [comment]
@cr8onski did you mean to close this without merging?

**Pull request merged**
