### PR TITLE
allow code 400 and version 0.9/5 in versioning tests

### PR DESCRIPTION
**Pull request by cr8onski**

### CODE REVIEW

**Comment by cr8onski** [comment]
fixes #184

**Comment by bscSCORM** [comment]
@cr8onski @ljwolford did you see my comment on the issue?

**Comment by bscSCORM** [comment]
Oh, yes, obviously you did, this looks like it should fix it, will check.

**Comment by ljwolford** [comment]
@bscSCORM yup give that a try. checks for 1.0.3 (or current), 0.9 and 0.95 for a 400 error and checks 0.9 or 0.95 if a 404 occurs

**Pull request merged**
